export const RAP_REDUX_REQUEST = 'RAP_REDUX_REQUEST'
export const RAP_REDUX_UPDATE_STORE = 'RAP_REDUX_UPDATE_STORE'
export const RAP_REDUX_CLEAR_STORE = 'RAP_REDUX_CLEAR_STORE'
export const RAP_STATE_KEY = '$rapperResponseData'
